export const SearchRouteData = [
  //Employee 
  { control: 'employee', name: "Dashboard", path: "/employee/dashboard" },
  { control: 'employee', name: "Education", path: "/employee/:id/education" },
  { control: 'employee', name: "Family", path: "/employee/:id/family-info" },
  { control: 'employee', name: "Experience", path: "/employee/:id/work-experience" },
  { control: 'employee', name: "Documents", path: "/employee/document" },
  { control: 'employee', name: "Personal Info", path: "/employee/:id/personal-info" },
  { control: 'employee', name: "Leave Application", path: "/employee/:id/leave-application-emp" },
  { control: 'employee', name: "My Attendance", path: "/employee/MyAttendance" },
  { control: 'employee', name: "Active Task", path: "/employee/activeTask" },
  { control: 'employee', name: "Task Complete", path: "/employee/taskcomplete" },
  { control: 'employee', name: "Task Reject", path: "/employee/taskreject" },
  { control: 'employee', name: "Birthday", path: "/employee/:id/birthday" },
  { control: 'employee', name: "Notification", path: "/employee/notification" },
  { control: 'employee', name: "New Task", path: "/employee/newTask" },

  //Manager 
  { control: 'manager', name: "Employee", path: "/manager/employee" },
  { control: 'manager', name: "Leave Application", path: "/manager/leaveApplication" },
  { control: 'manager', name: "Dashboard", path: "/manager/dashboard" },
  { control: 'manager', name: "New Task", path: "/manager/newTask" },
  { control: 'manager', name: "Active Task", path: "/manager/ActiveTask" },
  { control: 'manager', name: "Task Cancel", path: "/manager/taskcancle" },
  { control: 'manager', name: "Task Complete", path: "/manager/taskcomplete" },
  { control: 'manager', name: "Reject Task", path: "/manager/rejectTask" },
  { control: 'manager', name: "View Attendance", path: "/manager/viewAttenDance" },
  { control: 'manager', name: "My Attendance", path: "/manager/myAttendance" },
  { control: 'manager', name: "Notification", path: "/manager/notification" },
  { control: 'manager', name: "Create Leave", path: "/manager/createLeave" },
  { control: 'manager', name: "Personal Info", path: "/manager/personal-info" },
];